  - name: Download Golang 
    get_url:
      url: "https://storage.googleapis.com/golang/go{{go_version}}.linux-amd64.tar.gz"
      dest: "/tmp"
      mode: 0440
     
  - name: Remove old installation of Go
    file:
      path: "{{ go_install_dir }}/go"
      state: absent
    become: yes
 
  - name: Extract the Go tarball
    unarchive:
      src: "/tmp/go{{go_version}}.linux-amd64.tar.gz"
      dest: "{{ go_install_dir }}"
      copy: no
    become: yes
 
  - name: create go directories in home
    file:
      path: "{{item}}"
      state: directory
      owner: "root"
      group: "root"
      mode: 0775
    with_items:
    - "{{ home_dir }}/go"
    - "{{ home_dir }}/go/bin"
     
  - name: modify .bashrc
    blockinfile:
      dest: "{{ home_dir }}/.bashrc"
      block: |
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        export PATH=$GOBIN:$PATH:/usr/local/go/bin
      marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
      insertafter: EOF
      create: yes 

  # - name: Source the bashrc file
  #   shell: . "{{ home_dir }}/.bashrc"

  - name: Reload Path
    shell: source /root/.bashrc
    args:
      executable: /bin/bash
  - shell: echo $PATH
    register: pathul

  - debug: var=pathul.stdout_lines